import pygame

"""
MAKING SCREEN SQUARE SO THAT ALL CELL WILL BECOME SQUARE
"""
SCREEN_SIZE = 900

NUM_CELLS = 10
"""
MAKING BOARD SIZE EQUAL TO 70% WIDTH OF SCREEN SIZE
"""
BOARD_SIZE = int(SCREEN_SIZE * 1.7), int(SCREEN_SIZE * 1.7)
CELL_SIZE = BOARD_SIZE[0] // NUM_CELLS

"""
COLORS
"""
WHITE = (255, 255, 255, 255)
BLACK = (0, 0, 0, 255)
